version: "3"
services:
  producer:
    image: producer
    depends_on:
      - "rmq"
  consumer:
    image: consumer
    depends_on:
      - "rmq"
  rmq:
    image: rabbitmq
    ports:
      - "5672:5672"
